apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: precio
    version: v3
  name: precio-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: precio
      version: v3
  template:
    metadata:
      labels:
        app: precio
        version: v3
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xmx256m
        image: arielcarralbal/precio:v3
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        name: precio
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 10
        securityContext:
          privileged: false
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 500Mi
