apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: producto
    version: v1
  name: producto-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producto
      version: v1
  template:
    metadata:
      labels:
        app: producto
        version: v1
    spec:
      containers:
      - env:
        - name: JAVA_OPTIONS
          value: -Xms128m -Xmx256m -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:///dev/./urandom
        image: arielcarralbal/producto:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - curl
            - localhost:8080/actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
        name: producto
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8778
          name: jolokia
          protocol: TCP
        - containerPort: 9779
          name: prometheus
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - curl
            - localhost:8080/actuator/health
          initialDelaySeconds: 30
          periodSeconds: 5
          timeoutSeconds: 1
        securityContext:
          privileged: false
        resources:
          limits:
            cpu: 1
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 500Mi

