apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: preciorequestcount
  namespace: istio-system
spec:
  value: "1"
  dimensions:
    source: source.service | "unknown"
    destination: destination.service | "unknown"
    version: destination.labels["version"] | "unknown"
    user_agent: request.headers["user-agent"] | "unknown"
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: preciorequestcounthandler
  namespace: istio-system
spec:
  metrics:
  - name: precio_request_count
    instance_name: preciorequestcount.metric.istio-system
    kind: COUNTER
    label_names:
    - source
    - destination
    - user_agent
    - version
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: preciorequestcountprom
  namespace: istio-system
spec:
  match: destination.service == "precio.workshop.svc.cluster.local"
  actions:
  - handler: preciorequestcounthandler.prometheus
    instances:
    - preciorequestcount.metric
